import { defineConfig } from "tsup"

export default defineConfig({
  entry: [
    "src/index.ts",
    // Components
    "src/components/accordion.tsx",
    "src/components/alert.tsx",
    "src/components/alert-dialog.tsx",
    "src/components/aspect-ratio.tsx",
    "src/components/avatar.tsx",
    "src/components/badge.tsx",
    "src/components/breadcrumb.tsx",
    "src/components/button.tsx",
    "src/components/button-group.tsx",
    "src/components/calendar.tsx",
    "src/components/card.tsx",
    "src/components/carousel.tsx",
    "src/components/chart.tsx",
    "src/components/checkbox.tsx",
    "src/components/collapsible.tsx",
    "src/components/combobox.tsx",
    "src/components/command.tsx",
    "src/components/context-menu.tsx",
    "src/components/dialog.tsx",
    "src/components/direction.tsx",
    "src/components/drawer.tsx",
    "src/components/dropdown-menu.tsx",
    "src/components/empty.tsx",
    "src/components/field.tsx",
    "src/components/hover-card.tsx",
    "src/components/input.tsx",
    "src/components/input-group.tsx",
    "src/components/input-otp.tsx",
    "src/components/item.tsx",
    "src/components/kbd.tsx",
    "src/components/label.tsx",
    "src/components/menubar.tsx",
    "src/components/native-select.tsx",
    "src/components/navigation-menu.tsx",
    "src/components/pagination.tsx",
    "src/components/popover.tsx",
    "src/components/progress.tsx",
    "src/components/radio-group.tsx",
    "src/components/resizable.tsx",
    "src/components/scroll-area.tsx",
    "src/components/select.tsx",
    "src/components/separator.tsx",
    "src/components/sheet.tsx",
    "src/components/sidebar.tsx",
    "src/components/skeleton.tsx",
    "src/components/slider.tsx",
    "src/components/sonner.tsx",
    "src/components/spinner.tsx",
    "src/components/switch.tsx",
    "src/components/table.tsx",
    "src/components/tabs.tsx",
    "src/components/textarea.tsx",
    "src/components/toggle.tsx",
    "src/components/toggle-group.tsx",
    "src/components/tooltip.tsx",
    // Hooks
    "src/hooks/use-mobile.ts",
    // Utilities
    "src/lib/utils.ts",
  ],
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  splitting: false,
  external: [
    "react",
    "react-dom",
    "react/jsx-runtime",
    "@base-ui/react",
    "class-variance-authority",
    "clsx",
    "tailwind-merge",
    "lucide-react",
  ],
})
